const { REACT_APP_OPEN_WEATHER_BASE_URL, REACT_APP_OPEN_WEATHER_API_KEY } = process.env;

export const API_BASE_URL = REACT_APP_OPEN_WEATHER_BASE_URL;
export const API_KEY = REACT_APP_OPEN_WEATHER_API_KEY;